title: Окружение
views:

  - title: Окружение
    id: environment
    path: environment
    icon: mdi:oil-temperature
    panel: true
    cards:
      - type: custom:vertical-stack-in-card
        cards:
          - type: custom:vertical-stack-in-card
            title: Зал
            cards:
              - type: history-graph
                title: Температура
                hours_to_show: 24
                entities:
                  - entity: sensor.xiaomi_mijia_d107_temperature
                    name: Датчик
                  - entity: sensor.humidifier_1_temp
                    name: Увлажнитель
                  - entity: sensor.radiator_1_temp
                    name: Радиатор
                  - entity: sensor.hall_average_temperature
                    name: Среднее
                  - entity: sensor.hall_average_temperature_floating
                    name: Плавающее среднее
                  - entity: sensor.moes_radiator_actuator_1_position
                    name: Радиатор (положение)
              - type: history-graph
                title: Влажность
                hours_to_show: 24
                entities:
                  - entity: sensor.xiaomi_mijia_d107_humidity
                    name: Датчик
                  - entity: sensor.humidifier_1_hum
                    name: Увлажнитель
                  - entity: sensor.hall_average_humidity
                    name: Среднее
                  - entity: sensor.hall_average_humidity_floating
                    name: Плавающее среднее
          - type: custom:vertical-stack-in-card
            title: Спальня
            cards:
              - type: history-graph
                title: Температура
                hours_to_show: 24
                entities:
                  - entity: sensor.bedroom_temp_and_hum_temperature
                    name: Датчик
                  - entity: sensor.humidifier_2_temp
                    name: Увлажнитель
                  - entity: sensor.radiator_2_temp
                    name: Радиатор
                  - entity: sensor.bedroom_average_temperature
                    name: Среднее
                  - entity: sensor.bedroom_average_temperature_floating
                    name: Плавающее среднее
                  - entity: sensor.moes_radiator_actuator_2_position
                    name: Радиатор (положение)
              - type: history-graph
                title: Влажность
                hours_to_show: 24
                entities:
                  - entity: sensor.bedroom_temp_and_hum_humidity
                    name: Датчик
                  - entity: sensor.humidifier_2_hum
                    name: Увлажнитель
                  - entity: sensor.bedroom_average_humidity
                    name: Среднее
                  - entity: sensor.bedroom_average_humidity_floating
                    name: Плавающее среднее
          - type: custom:vertical-stack-in-card
            title: Кухня
            cards:
              - type: history-graph
                title: Температура
                hours_to_show: 24
                entities:
                  - entity: sensor.xiaomi_mijia_cb15_temperature
                    name: Датчик
                  - entity: sensor.radiator_3_temp
                    name: Радиатор
                  - entity: sensor.kitchen_average_temperature
                    name: Среднее
                  - entity: sensor.kitchen_average_temperature_floating
                    name: Плавающее среднее
                  - entity: sensor.moes_radiator_actuator_3_position
                    name: Радиатор (положение)
              - type: history-graph
                title: Влажность
                hours_to_show: 24
                entities:
                  - entity: sensor.xiaomi_mijia_cb15_humidity
                    name: Датчик
          - type: custom:vertical-stack-in-card
            title: Кабинет
            cards:
              - type: history-graph
                title: Температура
                hours_to_show: 24
                entities:
                  - entity: sensor.hall_mh_z19_temperature
                    name: Датчик
              - type: history-graph
                title: CO2
                hours_to_show: 24
                entities:
                  - entity: sensor.hall_mh_z19_co2
                    name: Датчик
              - type: history-graph
                title: Температура света
                hours_to_show: 24
                entities:
                  - entity: sensor.cabinet_desk_lamp_color_temp
                    name: Реал
                  - entity: sensor.cabinet_desk_lamp_adaptive_color_temp
                    name: Адапт
