title: Окружение
views:
  - !include environment/temperature.yaml
  - !include environment/humidity.yaml
  - !include environment/co2.yaml
  - !include environment/pressure.yaml
  - !include environment/motion.yaml
  - !include environment/doors.yaml
  - !include environment/radiator.yaml
  - !include environment/humidifier.yaml
  - !include environment/filter.yaml
  - !include environment/energy.yaml
  - !include environment/lights.yaml