
# Bedroom

- alias: Bedroom Switch Both
  id: Bedroom Switch Both
  trigger:
    - platform: state
      entity_id: sensor.bedroom_wall_switch_action
      to: 'single_both'
    - platform: state
      entity_id: sensor.bedroom_wall_switch_action
      to: 'single_right'
  action:
    - service: switch.toggle
      entity_id: switch.xiaomi_power_plug_1_switch

########################################################################

# Telegram

- alias: Telegram start
  id: Telegram start
  trigger:
    - platform: event
      event_type: telegram_command
      event_data:
        command: '/start'
  action:
    - service: telegram_bot.send_message
      data:
        target: '{{ trigger.event.data.chat_id }}'
        message: 'Командуй'
        keyboard: '/ping, /test, /alarm'

- alias: 'Telegram ping/pong'
  id: 'Telegram ping/pong'
  trigger:
    - platform: event
      event_type: telegram_command
      event_data:
        command: '/ping'
  action:
    - service: telegram_bot.send_message
      data:
        target: '{{ trigger.event.data.chat_id }}'
        message: 'pong'
        disable_notification: true

########################################################################

# Log

- alias: 'Log: Entrance door opened'
  id: 'Log: Entrance door opened'
  mode: single
  max_exceeded: silent
  trigger:
    - platform: state
      entity_id: binary_sensor.entance_door_button
      from: 'off'
      to: 'on'
  action:
    - service: notify.log
      data:
        message: "Входная дверь открыта"
    - service: notify.tv
      data:
        message: "Входная дверь открыта"
    # Подождать 5 секунд (throttle из-за mode = single + silent)
    - delay: 5

- alias: 'Log: Entrance door opened to long'
  id: 'Log: Entrance door opened to long'
  trigger:
    - platform: state
      entity_id: binary_sensor.entance_door_button
      to: 'on'
      for:
        minutes: 1
  action:
    - service: notify.sergey
      data:
        message: "Входная дверь открыта дольше минуты"
    - wait_for_trigger:
        - platform: state
          entity_id: binary_sensor.entance_door_button
          to: 'off'
    - service: notify.sergey
      data:
        message: "Входная дверь закрыта"

########################################################################

# Kitchen Water Leak Sensor

- alias: Notify about Kitchen Water Leak
  id: Notify about Kitchen Water Leak
  trigger:
    - platform: state
      entity_id: binary_sensor.kitchen_water_leak
      from: 'off'
      to: 'on'
  action:
    - service: notify.family
      data:
        message: "Протечка на кухне!"

- alias: Notify about Kitchen Water Leak Stop
  id: Notify about Kitchen Water Leak Stop
  trigger:
    - platform: state
      entity_id: binary_sensor.kitchen_water_leak
      from: 'on'
      to: 'off'
  action:
    - service: notify.family
      data:
        message: "Протечка на кухне устранена..."

########################################################################


