
# Bedroom

- alias: Bedroom Switch Both
  id: Bedroom Switch Both
  trigger:
    - platform: state
      entity_id: sensor.bedroom_wall_switch_action
      to: 'single_both'
    - platform: state
      entity_id: sensor.bedroom_wall_switch_action
      to: 'single_right'
  action:
    - service: switch.toggle
      entity_id: switch.xiaomi_power_plug_1_switch

########################################################################

# Telegram

- alias: Telegram start
  id: Telegram start
  trigger:
    - platform: event
      event_type: telegram_command
      event_data:
        command: '/start'
  action:
    - service: telegram_bot.send_message
      data:
        target: '{{ trigger.event.data.chat_id }}'
        message: 'Командуй'
        keyboard: '/ping, /test, /alarm'

- alias: 'Telegram ping/pong'
  id: 'Telegram ping/pong'
  trigger:
    - platform: event
      event_type: telegram_command
      event_data:
        command: '/ping'
  action:
    - service: telegram_bot.send_message
      data:
        target: '{{ trigger.event.data.chat_id }}'
        message: 'pong'
        disable_notification: true

########################################################################

# Log

- alias: 'Log: HA started'
  id: 'Log: HA started'
  trigger:
    # Запущен HA
    - platform: homeassistant
      event: start
  action:
    - service: notify.sergey
      data:
        message: "Запущен HA"
