
# Bedroom

- alias: Toggle Bedroom Mirror with Switch
  trigger:
    - platform: state
      entity_id: binary_sensor.bedroom_mirror_switch_contact
      from: 'on'
      to: 'off'
    - platform: state
      entity_id: binary_sensor.bedroom_mirror_switch_contact
      from: 'off'
      to: 'on'
  action:
    - service: switch.toggle
      entity_id: switch.xiaomi_socket_1

- alias: Bedroom Switch Both
  trigger:
    - platform: state
      entity_id: sensor.bedroom_wall_switch_action
      to: 'single_both'
    - platform: state
      entity_id: sensor.bedroom_wall_switch_action
      to: 'single_right'
  action:
    - service: switch.toggle
      entity_id: switch.xiaomi_power_plug_1_switch

########################################################################

# Bath + Toilet
# ToDo rework after real installation

- alias: Turn off Bath lights with Corridor Switch Bottom Left
  trigger:
    - platform: event
      event_type: zha_event
      event_data:
        device_ieee: 00:15:8d:00:04:9d:ec:35
        command: left_single
  condition:
    - condition: state
      entity_id: light.lumi_lumi_relay_c2acn01_2cd74b04_on_off
      state: 'on'
  action:
    - service: light.turn_off
      entity_id: light.lumi_lumi_relay_c2acn01_2cd74b04_on_off

- alias: Turn on Bath lights with Corridor Switch Bottom Left
  trigger:
    - platform: event
      event_type: zha_event
      event_data:
        device_ieee: 00:15:8d:00:04:9d:ec:35
        command: left_single
  condition:
    - condition: state
      entity_id: light.lumi_lumi_relay_c2acn01_2cd74b04_on_off
      state: 'off'
  action:
    - service: light.turn_on
      entity_id: light.lumi_lumi_relay_c2acn01_2cd74b04_on_off

- alias: Turn off Toilet lights with Corridor Switch Bottom Right
  trigger:
    - platform: event
      event_type: zha_event
      event_data:
        device_ieee: 00:15:8d:00:04:9d:ec:35
        command: right_single
  condition:
    - condition: state
      entity_id: light.lumi_lumi_relay_c2acn01_2cd74b04_on_off_2
      state: 'on'
  action:
    - service: light.turn_off
      entity_id: light.lumi_lumi_relay_c2acn01_2cd74b04_on_off_2

- alias: Turn on Toilet lights with Corridor Switch Bottom Right
  trigger:
    - platform: event
      event_type: zha_event
      event_data:
        device_ieee: 00:15:8d:00:04:9d:ec:35
        command: right_single
  condition:
    - condition: state
      entity_id: light.lumi_lumi_relay_c2acn01_2cd74b04_on_off_2
      state: 'off'
  action:
    - service: light.turn_on
      entity_id: light.lumi_lumi_relay_c2acn01_2cd74b04_on_off_2

- alias: Turn off Bath+Toilet lights with Corridor Switch Bottom Both
  trigger:
    - platform: event
      event_type: zha_event
      event_data:
        device_ieee: 00:15:8d:00:04:9d:ec:35
        command: both_single
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: light.lumi_lumi_relay_c2acn01_2cd74b04_on_off
        state: 'on'
      - condition: state
        entity_id: light.lumi_lumi_relay_c2acn01_2cd74b04_on_off_2
        state: 'on'
  action:
    - service: light.turn_off
      entity_id: light.lumi_lumi_relay_c2acn01_2cd74b04_on_off
    - service: light.turn_off
      entity_id: light.lumi_lumi_relay_c2acn01_2cd74b04_on_off_2

- alias: Turn on Bath+Toilet lights with Corridor Switch Bottom Both
  trigger:
    - platform: event
      event_type: zha_event
      event_data:
        device_ieee: 00:15:8d:00:04:9d:ec:35
        command: both_single
  condition:
    - condition: state
      entity_id: light.lumi_lumi_relay_c2acn01_2cd74b04_on_off
      state: 'off'
    - condition: state
      entity_id: light.lumi_lumi_relay_c2acn01_2cd74b04_on_off_2
      state: 'off'
  action:
    - service: light.turn_on
      entity_id: light.lumi_lumi_relay_c2acn01_2cd74b04_on_off
    - service: light.turn_on
      entity_id: light.lumi_lumi_relay_c2acn01_2cd74b04_on_off_2

########################################################################

# Telegram

- alias: 'Telegram start'
  trigger:
    - platform: event
      event_type: telegram_command
      event_data:
        command: '/start'
  action:
    - service: telegram_bot.send_message
      data:
        target: '{{ trigger.event.data.chat_id }}'
        message: 'Командуй'
        keyboard: '/ping, /test, /alarm'

- alias: 'Telegram ping/pong'
  trigger:
    - platform: event
      event_type: telegram_command
      event_data:
        command: '/ping'
  action:
    - service: telegram_bot.send_message
      data:
        target: '{{ trigger.event.data.chat_id }}'
        message: 'pong'
        disable_notification: true

########################################################################

# Log

- alias: 'Log: ToD.Night'
  trigger:
    - platform: state
      entity_id: binary_sensor.tod_night
      from: 'off'
      to: 'on'
  action:
    - service: notify.log
      data:
        message: "Началась ночь"

- alias: 'Log: ToD.Day'
  trigger:
    - platform: state
      entity_id: binary_sensor.tod_day
      from: 'off'
      to: 'on'
  action:
    - service: notify.log
      data:
        message: "Начался день"

- alias: 'Log: Entrance door opened'
  trigger:
    - platform: state
      entity_id: binary_sensor.door_window_sensor_158d0001fa3431
      from: 'off'
      to: 'on'
  action:
    - service: notify.log
      data:
        message: "Входная дверь открыта"
    - service: notify.tv
      data:
        message: "Входная дверь открыта"
      
- alias: 'Log: Entrance door closed'
  trigger:
    - platform: state
      entity_id: binary_sensor.door_window_sensor_158d0001fa3431
      from: 'on'
      to: 'off'
  action:
    - service: notify.log
      data:
        message: "Входная дверь закрыта"

########################################################################

# Kitchen Water Leak Sensor

- alias: 'Notify about Kitchen Water Leak'
  trigger:
    - platform: state
      entity_id: binary_sensor.kitchen_water_leak
      from: 'off'
      to: 'on'
  action:
    - service: notify.family
      data:
        message: "Протечка на кухне!"

- alias: 'Notify about Kitchen Water Leak Stop'
  trigger:
    - platform: state
      entity_id: binary_sensor.kitchen_water_leak
      from: 'on'
      to: 'off'
  action:
    - service: notify.family
      data:
        message: "Протечка на кухне устранена..."

########################################################################


