default_config:

# Компонент, позволяющий в автоматическом режиме находить ваши устройства в сети. Хорошо подтягивает Xiaomi zigbee устройства подключенные к шлюзу, сам шлюз, телеки известных фирм. Немного увеличивает время запуска HA 
# discovery:

tts:
  - platform: google_translate

lovelace:
  mode: yaml

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
zone: !include zones.yaml

panel_iframe:
  tasmoadmin:
    title: TasmoAdmin
    icon: mdi:lightbulb-on
    url: !secret tasmoadmin_host

xiaomi_aqara:
  discovery_retry: 5
  gateways:
    - key: !secret xiaomi_gateway_key
    
light:
  - platform: xiaomi_miio
    host: 192.168.1.41
    token: !secret xiaomi_bulb1_token
    model: philips.light.bulb

fan:
  - platform: xiaomi_miio
    host: 192.168.1.104
    model: zhimi.humidifier.ca1
    token: !secret xiaomi_humidifier_token

switch:
  - platform: broadlink
    host: 192.168.1.69
    mac: 'C8:F7:42:62:FB:3B'
    type: rm_mini
    timeout: 15
    switches:
      tv_power:
        friendly_name: "TV Power"
        command_on: 'JgDAAAABH5UVEBEUEjcVEBUQERQSEhITFTUROBEUEzYVNRE4ETgTNxUQERMTEhI4FRARExUQERQUNRI4ETgRFBQ2ETgROBI4FQAFIAABIUsSAAxQAAEmSxEADFAAASVMEQAMUQABJEwRAAxSAAElSxEADFYAASRMEQAMUQABJEwRAAxQAAElSxIADFMAASJLEQAMUQABJUsRAAxRAAElSxEADFAAASVLEQAMUQABJUsSAAxQAAEmSxEADFEAASVLEQANBQAAAAAAAAAA'
        command_off: 'JgDAAAABH5UVEBEUEjcVEBUQERQSEhITFTUROBEUEzYVNRE4ETgTNxUQERMTEhI4FRARExUQERQUNRI4ETgRFBQ2ETgROBI4FQAFIAABIUsSAAxQAAEmSxEADFAAASVMEQAMUQABJEwRAAxSAAElSxEADFYAASRMEQAMUQABJEwRAAxQAAElSxIADFMAASJLEQAMUQABJUsRAAxRAAElSxEADFAAASVLEQAMUQABJUsSAAxQAAEmSxEADFEAASVLEQANBQAAAAAAAAAA'

webostv:
  - host: 192.168.1.130
    name: TV
    turn_on_action:
      service: switch.toggle
      data:
        entity_id: switch.tv_power
    customize:
      sources:
        - HDMI1
        - HDMI2
        - HDMI3
        - HDMI4
        - LiveTV
        - MEGOGO TV & Movies
        - Netflix
        - Tvigle
        - YouTube
        - ivi

media_player:
  - platform: webostv
    host:  192.168.1.130
    name: TV

telegram_bot:
  - platform: webhooks
    url: !secret white_host
    api_key: !secret telegram_home_key
    allowed_chat_ids:
      - !secret telegram_chat_sergey
      - !secret telegram_chat_alexa
    trusted_networks:
      - 172.30.33.3/32
      - 149.154.160.0/20
      - 91.108.4.0/22

notify:
  - name: sergey
    platform: telegram
    chat_id: !secret telegram_chat_sergey
  - name: alexa
    platform: telegram
    chat_id: !secret telegram_chat_alexa
  - name: family
    platform: group
    services:
      - service: sergey
      - service: alexa
  - name: tv
    platform: webostv
    host: 192.168.1.130

timer: !include includes/timer.yaml

yandex_smart_home: