
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homeassistant:
  name: Home
  latitude: !secret lat
  longitude: !secret long
  elevation: 140
  unit_system: metric
  time_zone: Europe/Minsk
  external_url: !secret white_host
  internal_url: http://192.168.1.2:8123
  customize: !include customize.yaml
  packages: !include_dir_merge_named packages

# Text to speech
#tts:
#  - platform: google_translate

recorder:
  auto_purge: true
  purge_keep_days: 1
  commit_interval: 30
  include:
    domains:
      - light
      - switch
    entity_globs:
      - sensor.*_hum
      - sensor.*_humidity
      - sensor.*_humidity_floating
      - sensor.*_temp
      - sensor.*_temperature
      - sensor.*_temperature_floating
      - sensor.*_co2
      - sensor.*_co2_floating
      - sensor.*_power
      - sensor.*_action
    entities:
      # Person
      - person.sergey
      - person.alexa
      # Motion
      - binary_sensor.entrance_motion_sensor_occupancy
      - binary_sensor.rf_motion_0
      - binary_sensor.rf_motion_1
      # Water leak
      - binary_sensor.kitchen_water_leak
      # Smoke detection
      - binary_sensor.rf_smoke_0
      - binary_sensor.smoke_sensor_158d00041208c5
      # Reed switch
      - binary_sensor.door_window_sensor_158d0001fa3431
      # Illumination
      - sensor.illumination_7811dcb2404d
      # Radiator
      - sensor.radiator_1_position
      - sensor.radiator_2_position
      - sensor.radiator_3_position
      # Humidifier
      - fan.humidifier_1
      - fan.humidifier_2
      # Filter
      - sensor.drink_water_drink_filter
      - sensor.raw_water_drink_filter

lovelace:
  mode: yaml

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

mqtt:
  broker: core-mosquitto  # Локальный брокер
  #broker: IP adress  # Внешний брокер
  discovery: true
  discovery_prefix: homeassistant  
  username: mqtt
  password: mqtt

yeelight:
  devices:
    192.168.1.226:
      name: Kitchen Ceiling
      save_on_change: true
      nightlight_switch_type: light
      model: ceiling3
    192.168.1.182:
      name: Cabinet Desk Lamp
      save_on_change: true
      model: lamp1

light:
  - platform: xiaomi_miio
    host: 192.168.1.44
    token: !secret xiaomi_bulb1_token
    model: philips.light.bulb
  - platform: switch
    name: Kitchen 2 Relay L1
    entity_id: switch.kitchen_2_relay_l1
  - platform: switch
    name: Kitchen 2 Relay L2
    entity_id: switch.kitchen_2_relay_l2

fan:
  - platform: xiaomi_miio
    host: 192.168.1.104
    model: zhimi.humidifier.ca1
    name: "Humidifier #1"
    token: !secret xiaomi_humidifier1_token
  - platform: xiaomi_miio
    host: 192.168.1.203
    model: zhimi.humidifier.ca1
    name: "Humidifier #2"
    token: !secret xiaomi_humidifier2_token


binary_sensor:
  - platform: tod
    name: tod_night
    after: '00:00'
    before: '07:00'
  - platform: tod
    name: tod_day
    after: '07:00'
    before: '00:00'
  - platform: template
    sensors:
      kitchen_motion:
        unique_id: kitchen_motion
        friendly_name: "Kitchen Motion"
        device_class: motion
        value_template: "{{ is_state('binary_sensor.rf_motion_0', 'on') or is_state('binary_sensor.rf_motion_1', 'on') }}"
        availability_template: "{{ not is_state('binary_sensor.rf_motion_0', 'unavailable') or not is_state('binary_sensor.rf_motion_1', 'unavailable') }}"

telegram_bot:
  - platform: webhooks
    api_key: !secret telegram_home_key
    allowed_chat_ids:
      - !secret telegram_chat_sergey
      - !secret telegram_chat_alexa
      - !secret telegram_chat_log
    trusted_networks:
      - 172.30.33.2/32
      - 172.30.33.3/32
      - 149.154.160.0/20
      - 91.108.4.0/22
      - 149.154.160.0/20
      - 91.108.4.0/22

camera:
  - platform: ffmpeg
    name: Sonoff-Camera-1
    input: -rtsp_transport tcp -i rtsp://rtsp:sonoff@192.168.1.93:554/av_stream/ch0

switch:
  - platform: broadlink
    mac: 'C8:F7:42:62:FB:3B'
    switches:
      - name: "TV Power"
        command_on: !secret ir_tv_power
        command_off: !secret ir_tv_power

sensor:
  - platform: template
    sensors:
      radiator_1_position:
        unique_id: radiator_1_position
        friendly_name: "Radiator Actuator #1 Position"
        unit_of_measurement: '%'
        value_template: "{{ state_attr('climate.moes_radiator_actuator_1_climate', 'position') }}"
        availability_template: "{{ not is_state('climate.moes_radiator_actuator_1_climate', 'unavailable') }}"
      radiator_1_temp:
        unique_id: radiator_1_current_temperature
        friendly_name: "Radiator Actuator #1 Current Temperature"
        unit_of_measurement: '°C'
        value_template: "{{ state_attr('climate.moes_radiator_actuator_1_climate', 'current_temperature') }}"
        availability_template: "{{ not is_state('climate.moes_radiator_actuator_1_climate', 'unavailable') }}"
      radiator_2_position:
        unique_id: radiator_2_position
        friendly_name: "Radiator Actuator #2 Position"
        unit_of_measurement: '%'
        value_template: "{{ state_attr('climate.moes_radiator_actuator_2_climate', 'position') }}"
        availability_template: "{{ not is_state('climate.moes_radiator_actuator_2_climate', 'unavailable') }}"
      radiator_2_temp:
        unique_id: radiator_2_current_temperature
        friendly_name: "Radiator Actuator #2 Current Temperature"
        unit_of_measurement: '°C'
        value_template: "{{ state_attr('climate.moes_radiator_actuator_2_climate', 'current_temperature') }}"
        availability_template: "{{ not is_state('climate.moes_radiator_actuator_2_climate', 'unavailable') }}"
      radiator_3_position:
        unique_id: radiator_3_position
        friendly_name: "Radiator Actuator #3 Position"
        unit_of_measurement: '%'
        value_template: "{{ state_attr('climate.moes_radiator_actuator_3_climate', 'position') }}"
        availability_template: "{{ not is_state('climate.moes_radiator_actuator_3_climate', 'unavailable') }}"
      radiator_3_temp:
        unique_id: radiator_3_current_temperature
        friendly_name: "Radiator Actuator #3 Current Temperature"
        unit_of_measurement: '°C'
        value_template: "{{ state_attr('climate.moes_radiator_actuator_3_climate', 'current_temperature') }}"
        availability_template: "{{ not is_state('climate.moes_radiator_actuator_3_climate', 'unavailable') }}"
      humidifier_1_temp:
        unique_id: humidifier_1_temp
        friendly_name: "Humidifier #1 Temperature"
        unit_of_measurement: '°C'
        value_template: "{{ state_attr('fan.humidifier_1', 'temperature') }}"
        availability_template: "{{ not is_state('fan.humidifier_1', 'unavailable') }}"
      humidifier_1_hum:
        unique_id: humidifier_1_hum
        friendly_name: "Humidifier #1 Humidity"
        unit_of_measurement: '%'
        value_template: "{{ state_attr('fan.humidifier_1', 'humidity') }}"
        availability_template: "{{ not is_state('fan.humidifier_1', 'unavailable') }}"
      humidifier_2_temp:
        unique_id: humidifier_2_temp
        friendly_name: "Humidifier #2 Temperature"
        unit_of_measurement: '°C'
        value_template: "{{ state_attr('fan.humidifier_2', 'temperature') }}"
        availability_template: "{{ not is_state('fan.humidifier_2', 'unavailable') }}"
      humidifier_2_hum:
        unique_id: humidifier_2_hum
        friendly_name: "Humidifier #2 Humidity"
        unit_of_measurement: '%'
        value_template: "{{ state_attr('fan.humidifier_2', 'humidity') }}"
        availability_template: "{{ not is_state('fan.humidifier_2', 'unavailable') }}"
  - platform: average
    name: 'Hall Average Temperature'
    precision: 1
    duration:
      minutes: 5
    entities:
      - sensor.xiaomi_mijia_d107_temperature
      - sensor.humidifier_1_temp
  - platform: average
    name: 'Hall Average Humidity'
    precision: 1
    duration:
      minutes: 5
    entities:
      - sensor.xiaomi_mijia_d107_humidity
      - sensor.humidifier_1_hum
  - platform: average
    name: 'Bedroom Average Temperature'
    precision: 1
    duration:
      minutes: 5
    entities:
      - sensor.bedroom_temp_and_hum_temperature
      - sensor.humidifier_2_temp
  - platform: average
    name: 'Bedroom Average Humidity'
    precision: 1
    duration:
      minutes: 5
    entities:
      - sensor.bedroom_temp_and_hum_humidity
      - sensor.humidifier_2_hum

webostv:
  - host: 192.168.1.130
    name: TV
    turn_on_action:
      service: switch.toggle
      data:
        entity_id: switch.tv_power
    customize:
      sources:
        - HDMI1
        - HDMI2
        - HDMI3
        - HDMI4
        - LiveTV
        - MEGOGO TV & Movies
        - Netflix
        - Tvigle
        - YouTube
        - ivi
        - Kinopoisk HD

media_player:
  - platform: webostv
    host:  192.168.1.130
    name: TV

yandex_station:
  username: !secret ya_username
  password: !secret ya_password
yandex_smart_home_fix:
yandex_smart_home:
  filter:
    include_domains:
    include_entities:
      - switch.cupboard_relay
      - switch.hall_wall_switch_left
      - switch.hall_wall_switch_right
      - switch.bra2_relay
      - switch.bedroom_wall_switch_left
      - switch.xiaomi_power_plug_1_switch
      - switch.mirror_relay
      - switch.entrance_wall_switch_right
      - switch.entrance_wall_switch_left
      - light.xiaomi_philips_light
      - light.wled_maria_bed
      - light.wled_tree
      - light.kitchen_ceiling
      - light.kitchen_ceiling_nightlight
      - switch.kitchen_2_relay_l1
      - switch.kitchen_2_relay_l2
      - light.cabinet_desk_lamp
      - light.xiaomi_gateway_light
      - media_player.tv
      - sensor.bedroom_average_temperature_floating
  entity_config:
    switch.cupboard_relay:
      type: devices.types.light
      name: 'Шкаф'
      room: 'Кабинет'
    switch.hall_wall_switch_left:
      type: devices.types.light
      name: 'Люстра 2'
      room: 'Зал'
    switch.hall_wall_switch_right:
      type: devices.types.light
      name: 'Люстра 3'
      room: 'Зал'
    switch.bra2_relay:
      type: devices.types.light
      name: 'Бра 2'
      room: 'Зал'
    switch.bedroom_wall_switch_left:
      type: devices.types.light
      name: 'Свет'
      room: 'Спальня'
    switch.xiaomi_power_plug_1_switch:
      type: devices.types.light
      name: 'Кровать'
      room: 'Спальня'
    switch.mirror_relay:
      type: devices.types.light
      name: 'Зеркало'
      room: 'Спальня'
    switch.entrance_wall_switch_right:
      type: devices.types.light
      name: 'Свет'
      room: 'Прихожая'
    switch.entrance_wall_switch_left:
      type: devices.types.light
      name: 'Свет'
      room: 'Коридор'
    light.xiaomi_philips_light:
      type: devices.types.light
      name: 'Бра 1'
      room: 'Зал'
    light.wled_maria_bed:
      type: devices.types.light
      name: 'Ночник'
      room: 'Спальня'
    light.wled_tree:
      type: devices.types.light
      name: 'Ёлка'
      room: 'Зал'
    light.kitchen_ceiling:
      type: devices.types.light
      name: 'Свет'
      room: 'Кухня'
    light.kitchen_ceiling_nightlight:
      type: devices.types.light
      name: 'Луна'
      room: 'Кухня'
    switch.kitchen_2_relay_l1:
      type: devices.types.light
      name: 'Гирлянда'
      room: 'Кухня'
    switch.kitchen_2_relay_l2:
      type: devices.types.light
      name: 'Подсветка'
      room: 'Кухня'
    light.cabinet_desk_lamp:
      type: devices.types.light
      name: 'Настольная лампа'
      room: 'Кабинет'
    light.xiaomi_gateway_light:
      type: devices.types.light
      name: 'Шайба'
      room: 'Прихожая'
    media_player.tv:
      type: devices.types.media_device.tv
      name: 'Телевизор'
      room: 'Зал'
    sensor.bedroom_average_temperature_floating:
      type: devices.types.sensor
      name: 'Температура'
      room: 'Спальня'
      

notify:
  - name: sergey
    platform: telegram
    chat_id: !secret telegram_chat_sergey
  - name: alexa
    platform: telegram
    chat_id: !secret telegram_chat_alexa
  - name: log
    platform: telegram
    chat_id: !secret telegram_chat_log
  - name: family
    platform: group
    services:
      - service: sergey
      - service: alexa
  - name: tv
    platform: webostv
    host: 192.168.1.130