# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
zone: !include zones.yaml

panel_iframe:
  tasmoadmin:
    title: TasmoAdmin
    icon: mdi:lightbulb-on
    url: !secret tasmoadmin_host

# You can leave MAC empty if you only have one gateway.
xiaomi_aqara:
  discovery_retry: 5
  gateways:
    - key: !secret xiaomi_gateway_key
    
light:
  - platform: xiaomi_miio
    host: 192.168.1.41
    token: !secret xiaomi_bulb1_token
    model: philips.light.bulb
  - platform: mqtt
    schema: json
    name: "ESP LEDs"
    state_topic: "espleds/state"
    command_topic: "espleds/set"
    availability_topic: "espleds/LWT"
    effect: true
    effect_list:
      - bpm
      - candy cane  
      - confetti  
      - cyclon rainbow  
      - dots  
      - fire  
      - glitter  
      - juggle  
      - lightning
      - noise  
      - police all  
      - police one  
      - rainbow  
      - rainbow with glitter  
      - ripple  
      - sinelon  
      - solid  
      - twinkle  
    brightness: true
    # flash: true
    rgb: true
    payload_available: "Online"
    payload_not_available: "Offline"
    optimistic: false
    qos: 1

input_number:
  espleds_animation_speed:
    name: ESP LEDs Animation Speed
    initial: 150
    min: 1
    max: 150
    step: 10

fan:
  - platform: xiaomi_miio
    host: 192.168.1.104
    model: zhimi.humidifier.ca1
    token: !secret xiaomi_humidifier_token

switch:
  - platform: mqtt
    name: "Зеркало"
    state_topic: "dressingroom/mirror/stat/RESULT"
    value_template: "{{ value_json.POWER }}"
    command_topic: "dressingroom/mirror/cmnd/POWER"
    availability_topic: "dressingroom/mirror/tele/LWT"
    state_on: "ON"
    state_off: "OFF"
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    optimistic: false
    qos: 1
    retain: false
  - platform: mqtt
    name: "Шкаф"
    state_topic: "dressingroom/cupboard/stat/RESULT"
    value_template: "{{ value_json.POWER }}"
    command_topic: "dressingroom/cupboard/cmnd/POWER"
    availability_topic: "dressingroom/cupboard/tele/LWT"
    state_on: "ON"
    state_off: "OFF"
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    optimistic: false
    qos: 1
    retain: false

media_player:
  - platform: webostv
    host:  192.168.1.130
    name: TV
    filename: webostv.conf
    timeout: 5

telegram_bot:
  # Home
  - platform: polling
    api_key: !secret telegram_home_key
    allowed_chat_ids:
      - !secret telegram_chat_sergey
      - !secret telegram_chat_alexa
  # Home Log
  - platform: polling
    api_key: !secret telegram_log_key
    allowed_chat_ids:
      - !secret telegram_chat_log

notify:
  - name: log
    platform: telegram
    chat_id: !secret telegram_chat_log
  - name: sergey
    platform: telegram
    chat_id: !secret telegram_chat_sergey
  - name: alexa
    platform: telegram
    chat_id: !secret telegram_chat_alexa
  - name: family
    platform: group
    services:
      - service: sergey
      - service: alexa
  - name: tv
    platform: webostv
    host: 192.168.1.130
    filename: webostv.conf

timer: !include includes/timer.yaml

yandex_smart_home: