esphome:
  name: bluetooth_hub
  platform: ESP32
  board: nodemcu-32s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pwd

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "BluetoothHub Fallback Hotspot"
    password: !secret esphome_pwd

captive_portal:

web_server:
  port: 80
  auth:
    username: admin
    password: !secret esphome_pwd
    
# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret esphome_pwd

ota:
  password: !secret esphome_pwd

uart:
  rx_pin: 17
  tx_pin: 5
  baud_rate: 9600

esp32_ble_tracker:

sensor:
  - platform: mhz19
    co2:
      name: "MH-Z19 (1) CO2"
    temperature:
      name: "MH-Z19 (1) Temperature"
    update_interval: 30s
    automatic_baseline_calibration: false
  - platform: xiaomi_lywsdcgq
    mac_address: 58:2D:34:35:D1:07
    temperature:
      name: "Xiaomi MiJia D107 Temperature"
    humidity:
      name: "Xiaomi MiJia D107 Humidity"
    battery_level:
      name: "Xiaomi MiJia D107 Battery Level"
  - platform: xiaomi_lywsd03mmc
    mac_address: "A4:C1:38:48:8E:CF"
    bindkey: "37d352a5b30c9001bd2e897452e06dff"   
    temperature:
      name: "Xiaomi MiJia 8ECF Temperature"
    humidity:
      name: "Xiaomi MiJia 8ECF Humidity"
    battery_level:
      name: "Xiaomi MiJia 8ECF Battery Level"
  - platform: xiaomi_lywsd03mmc
    mac_address: "A4:C1:38:D6:4A:07"
    bindkey: "01bbf4c74fa5df89c33dacb6fab0100f"   
    temperature:
      name: "Xiaomi MiJia 4A07 Temperature"
    humidity:
      name: "Xiaomi MiJia 4A07 Humidity"
    battery_level:
      name: "Xiaomi MiJia 4A07 Battery Level"
  - platform: xiaomi_lywsd03mmc
    mac_address: "A4:C1:38:9A:A8:10"
    bindkey: "448c7f8981c96c9d4c9c73e373d256fe"   
    temperature:
      name: "Xiaomi MiJia A810 Temperature"
    humidity:
      name: "Xiaomi MiJia A810 Humidity"
    battery_level:
      name: "Xiaomi MiJia A810 Battery Level"
  - platform: xiaomi_lywsd03mmc
    mac_address: "A4:C1:38:96:A4:DB"
    bindkey: "3876d722b1081528617c025c760023b3"   
    temperature:
      name: "Xiaomi MiJia A4DB Temperature"
    humidity:
      name: "Xiaomi MiJia A4DB Humidity"
    battery_level:
      name: "Xiaomi MiJia A4DB Battery Level"