esphome:
  name: bluetooth_hub
  platform: ESP32
  board: esp-wrover-kit

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pwd

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "BluetoothHub Fallback Hotspot"
    password: !secret esphome_pwd

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret esphome_pwd

ota:
  password: !secret esphome_pwd

esp32_ble_tracker:
  scan_interval: 300s

sensor:
  - platform: xiaomi_mijia
    mac_address: 58:2D:34:35:CB:15
    temperature:
      name: "Xiaomi MiJia CB15 Temperature"
    humidity:
      name: "Xiaomi MiJia CB15 Humidity"
    battery_level:
      name: "Xiaomi MiJia CB15 Battery Level"
  - platform: xiaomi_mijia
    mac_address: 58:2D:34:35:D1:07
    temperature:
      name: "Xiaomi MiJia D107 Temperature"
    humidity:
      name: "Xiaomi MiJia D107 Humidity"
    battery_level:
      name: "Xiaomi MiJia D107 Battery Level"