esphome:
  name: bra2
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pwd

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Bra2 Fallback Hotspot"
    password: !secret esphome_pwd

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret esphome_pwd

ota:
  password: !secret esphome_pwd

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO5
    name: "Bra2 Button"
    on_state:
      - switch.toggle: fakebutton

switch:
  - platform: template
    name: "Bra2 Relay"
    optimistic: true
    id: fakebutton
    turn_on_action:
    - switch.turn_on: relay
    turn_off_action:
    - switch.turn_off: relay
  - platform: gpio
    id: relay
    pin: GPIO4