esphome:
  name: entance_door_light
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pwd

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Entance Door Fallback Hotspot"
    password: !secret esphome_pwd

captive_portal:

web_server:
  port: 80
  auth:
    username: admin
    password: !secret esphome_pwd

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret esphome_pwd

ota:
  password: !secret esphome_pwd

binary_sensor:
  - platform: gpio
    id: button
    device_class: door
    pin:
      number: GPIO5
    name: "Entance Door Button"
    filters:
      - delayed_off: 3s
    on_press:
      then:
        - switch.turn_on: relay
        - switch.template.publish:
            id: fake
            state: ON
    on_release:
      then:
        - switch.turn_off: relay
        - switch.template.publish:
            id: fake
            state: OFF

switch:
  - platform: template
    name: "Entance Door Light"
    optimistic: false
    id: fake
    turn_on_action:
      - switch.turn_on: relay
      - switch.template.publish:
          id: fake
          state: ON
    turn_off_action:
      if:
        condition:
          binary_sensor.is_off: button
        then:
          - switch.turn_off: relay
          - switch.template.publish:
              id: fake
              state: OFF
        else:
          - switch.template.publish:
              id: fake
              state: ON
  - platform: gpio
    id: relay
    pin: GPIO4