# Smart Intercom project
# https://github.com/Anonym-tsk/smart-domofon/tree/master/ge1mer

############# User configuration #############

substitutions:
  # Ge1mer board
  board: esp12e
  pin_relay_answer: GPIO14    # 330 Ohm, NO relay
  pin_relay_phone: GPIO16     # Intercom, NC relay
  pin_relay_mute: GPIO12      # 50 Ohm, NO relay
  pin_led_red: GPIO5
  pin_led_green: GPIO4
  pin_led_blue: GPIO15
  pin_call_detect: GPIO13
  pin_btn_accept: GPIO0

  # Board name
  board_name: "intercom"
  mdns_name: "intercom"

  # Relays configuration
  phone_relay_inverted: 'true'  # Set to 'false' if you have NO phone relay

  # Wifi credentials
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_pwd
  ap_ssid: "Intercom Fallback"
  ap_password: !secret esphome_pwd

  # Web
  web_user: admin
  web_password: !secret esphome_pwd

  # OTA and API
  ota_password: !secret esphome_pwd
  api_password: !secret esphome_pwd

  # Software configuration
  call_end_detect_delay: 3000ms     # Interval between rings to detect incoming call
  relay_before_answer_delay: 400ms  # Delay before answer call
  relay_answer_on_time: 5000ms      # Delay between answer call and open/close door
  relay_open_on_time: 5000ms         # How long the "open door button" will be pressed
  relay_after_open_delay: 5000ms     # Delay in "answer" state after opening door
  short_click_time_from: 10ms       # Short button click min time
  short_click_time_to: 1000ms       # Long button click min time

  # Led configuration
  led_brightness: "0.7"

########### End user configuration ###########

packages:
  base: !include intercom_packages/base.yaml
  api: !include intercom_packages/api.yaml
#  mqtt: !include intercom_packages/mqtt.yaml
  script: !include intercom_packages/script.yaml
  output: !include intercom_packages/output.yaml
  switch: !include intercom_packages/switch.yaml
  light: !include intercom_packages/light.yaml
  binary_sensor: !include intercom_packages/binary_sensor.yaml
