esphome:
  name: kitchen_esp32
  platform: ESP32
  board: nodemcu-32s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pwd

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Kitchen Esp32 Fallback Hotspot"
    password: !secret esphome_pwd

captive_portal:

web_server:
  port: 80
  auth:
    username: admin
    password: !secret esphome_pwd
    
# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret esphome_pwd

ota:
  password: !secret esphome_pwd

esp32_ble_tracker:

bluetooth_proxy:
  active: true

sensor:
  - platform: xiaomi_lywsdcgq
    mac_address: 58:2D:34:35:CB:15
    temperature:
      name: "Xiaomi MiJia CB15 Temperature"
    humidity:
      name: "Xiaomi MiJia CB15 Humidity"
    battery_level:
      name: "Xiaomi MiJia CB15 Battery Level"
  - platform: xiaomi_lywsd03mmc
    mac_address: "A4:C1:38:72:30:D0"
    bindkey: "174fc465e83cd0ba0f7ef3564359df5f"
    temperature:
      name: "Xiaomi MiJia 30D0 Temperature"
    humidity:
      name: "Xiaomi MiJia 30D0 Humidity"
    battery_level:
      name: "Xiaomi MiJia 30D0 Battery Level"
  - platform: xiaomi_lywsd03mmc
    mac_address: "A4:C1:38:9A:A8:10"
    bindkey: "448c7f8981c96c9d4c9c73e373d256fe"   
    temperature:
      name: "Xiaomi MiJia A810 Temperature"
    humidity:
      name: "Xiaomi MiJia A810 Humidity"
    battery_level:
      name: "Xiaomi MiJia A810 Battery Level"
  - platform: xiaomi_lywsd03mmc
    mac_address: "A4:C1:38:D6:4A:07"
    bindkey: "01bbf4c74fa5df89c33dacb6fab0100f"   
    temperature:
      name: "Xiaomi MiJia 4A07 Temperature"
    humidity:
      name: "Xiaomi MiJia 4A07 Humidity"
    battery_level:
      name: "Xiaomi MiJia 4A07 Battery Level"

binary_sensor:
  - platform: xiaomi_mjyd02yla
    name: "Xiaomi MiJia 70F0 Motion"
    mac_address: "28:D1:27:3C:70:F0"
    bindkey: "fc68f1452c86879501cde2dcb3c571df"
    idle_time:
      name: "Xiaomi MiJia 70F0 Idle Time"
    light:
      name: "Xiaomi MiJia 70F0 Light Status"
    battery_level:
      name: "Xiaomi MiJia 70F0 Battery Level"
    illuminance:
      name: "Xiaomi MiJia 70F0 Illuminance"